name: Feature request
description: Suggest an idea or improvement
title: 'feat: '
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What's the user pain you're trying to solve?
    validations: { required: true }
  - type: textarea
    attributes:
      label: Proposal
      description: How would you solve it?
    validations: { required: true }
  - type: textarea
    attributes:
      label: Alternatives considered
